DELETE FROM MEMBER WHERE USER_NO='22';

SELECT USER_ID, USER_PWD, USER_NAME
FROM MEMBER
WHERE USER_ID=? AND USER_PWD=? AND STATUS='Y';

SELECT USER_ID, USER_PWD, USER_NAME, EMAIL, GENDER
   				, TO_DATE(BIRTHDAY, 'rrmmdd'), PHONE, ADDRESS
FROM MEMBER
WHERE USER_ID= 'admin' AND USER_PWD= '1234' AND STATUS='Y';


SELECT * FROM MEMBER;