CREATE USER C##LYN IDENTIFIED BY LYN;
GRANT CONNECT, RESOURCE TO C##LYN;
ALTER USER C##LYN QUOTA UNLIMITED ON USERS;

DROP TABLE GAME;

CREATE TABLE GAME(
    GAME_ID VARCHAR2(10) PRIMARY KEY,
    TITLE VARCHAR2(50) NOT NULL,
    GENRE VARCHAR2(20) NOT NULL,
    PLATFORM VARCHAR2(30),
    RELEASE_DATE VARCHAR2(10)
);

COMMENT ON COLUMN GAME.GAME_ID IS '게임 번호'; 
COMMENT ON COLUMN GAME.TITLE IS '게임명'; 
COMMENT ON COLUMN GAME.GENRE IS '장르'; 
COMMENT ON COLUMN GAME.PLATFORM IS '플랫폼'; 
COMMENT ON COLUMN GAME.RELEASE_DATE IS '출시일'; 

DROP SEQUENCE SEQ_GAMEID;
CREATE SEQUENCE SEQ_GAMEID
START WITH 1001
NOCYCLE
NOCACHE;

INSERT INTO GAME VALUES('g_'||SEQ_GAMEID.NEXTVAL, '마인크래프트', '샌드박스', 'PC, Mobile, PS', TO_CHAR(TO_DATE('111118', 'YYMMDD'), 'YYYY-MM-DD'));
INSERT INTO GAME VALUES('g_'||SEQ_GAMEID.NEXTVAL, '리그 오브 레전드', 'MOBA', 'PC', TO_CHAR(TO_DATE('111204', 'YYMMDD'), 'YYYY-MM-DD'));
INSERT INTO GAME VALUES('g_'||SEQ_GAMEID.NEXTVAL, '젤다의 전설: 야생의 숨결', '액션 어드벤처', 'Nintendo Switch', TO_CHAR(TO_DATE('180201', 'YYMMDD'), 'YYYY-MM-DD'));
SELECT * FROM GAME;
SELECT * FROM GAME WHERE TITLE LIKE '%마인크래프트%';
COMMIT;