CREATE USER C##KH IDENTIFIED BY "KH";
GRANT CONNECT, RESOURCE TO C##KH;
ALTER USER C##KH DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

CREATE USER C##spring IDENTIFIED BY "spring";
GRANT CONNECT, RESOURCE TO C##spring;
ALTER USER C##spring DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;