SELECT EMP_ID
				, EMP_NAME
				, NVL(DEPT_TITLE,'미지정')DEPT_TITLE
				, JOB_NAME
				, TO_CHAR(HIRE_DATE, 'YYYY-MM-DD')HIRE_DATE
  		FROM EMPLOYEE
    		LEFT JOIN DEPARTMENT ON DEPT_CODE=DEPT_ID
    		JOIN JOB USING (JOB_CODE)
		WHERE ENT_YN ='N'
		ORDER BY EMP_ID;
        
SELECT EMP_NAME,DEPT_ID, DEPT_TITLE, LOCATION_ID, NATIONAL_NAME 
FROM DEPARTMENT
JOIN EMPLOYEE ON  DEPT_ID = DEPT_CODE 
JOIN LOCATION ON LOCATION_ID = LOCAL_CODE
JOIN NATIONAL USING (NATIONAL_CODE) 
ORDER BY NATIONAL_NAME DESC;