CREATE TABLE MENU(
    MENU_ID NUMBER PRIMARY KEY,
    CATEGORY VARCHAR2(30) NOT NULL,
    MENU_NAME VARCHAR2(30) NOT NULL,
    PRICE NUMBER
);

SELECT * FROM MENU ORDER BY MENU_ID;

INSERT INTO MENU VALUES (101, '커피', '아메리카노', 3000);
INSERT INTO MENU VALUES (102, '커피', '라떼', 3500);
INSERT INTO MENU VALUES (103, '커피', '모카', 4000);
INSERT INTO MENU VALUES (104, '커피', '에스프레소', 2500);
INSERT INTO MENU VALUES (105, '커피', '바닐라플렛화이트', 4500);
INSERT INTO MENU VALUES (106, '커피', '돌체라떼', 4300);

INSERT INTO MENU VALUES (201, '논커피', '티라떼', 4000);
INSERT INTO MENU VALUES (202, '논커피', '딸기라떼', 4500);
INSERT INTO MENU VALUES (203, '논커피', '초코라떼', 4300);
INSERT INTO MENU VALUES (204, '논커피', '자몽허니블랙티', 4800);

INSERT INTO MENU VALUES (301, '에이드', '자몽에이드', 5000);
INSERT INTO MENU VALUES (302, '에이드', '레몬에이드', 5000);
INSERT INTO MENU VALUES (303, '에이드', '포도에이드', 5000);

INSERT INTO MENU VALUES (401, '디저트', '초코파이', 2500);
INSERT INTO MENU VALUES (402, '디저트', '초코케이크', 5500);
INSERT INTO MENU VALUES (403, '디저트', '딸기생크림케이크', 6000);
/*
ROLLBACK;

SELECT * FROM MENU WHERE CATEGORY = '커피';

SELECT *
FROM MENU
WHERE PRICE <=5000 OR CATEGORY='디저트';

UPDATE MENU
    SET PRICE = 3000
    WHERE MENU_NAME ='아메리카노';
    
DELETE FROM MENU
    WHERE MENU_NAME='돌체라떼';
*/
COMMENT ON COLUMN MENU.MENU_ID IS '메뉴번호';
COMMENT ON COLUMN MENU.CATEGORY IS '카테고리';
COMMENT ON COLUMN MENU.MENU_NAME IS '메뉴명';
COMMENT ON COLUMN MENU.PRICE IS '가격';

SELECT * FROM MENU;

CREATE TABLE ORDERED_MENU(
    ORDERED_MENU_NAME VARCHAR2(30),
    TOTAL_PRICE NUMBER
);

COMMENT ON COLUMN ORDERED_MENU.ORDERED_MENU_NAME IS '주문한 메뉴명';
COMMENT ON COLUMN ORDERED_MENU.TOTAL_PRICE IS '메뉴 총 가격';
