/* WORKBOOK 계정 */
SELECT * FROM TB_STUDENT;
SELECT * FROM TB_PROFESSOR;
SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_GRADE;
SELECT * FROM TB_CLASS;
SELECT * FROM TB_CLASS_PROFESSOR;

-- 1.
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS 주소지
  FROM TB_STUDENT
 ORDER BY 1;
 
-- 2.
SELECT STUDENT_NAME, STUDENT_SSN
  FROM TB_STUDENT
 WHERE ABSENCE_YN = 'Y'
 ORDER BY SUBSTR(STUDENT_SSN, 1, 6) DESC;
 
-- 3. 
SELECT STUDENT_NAME 학생이름, STUDENT_NO 학번, STUDENT_ADDRESS "거주지 주소"
  FROM TB_STUDENT
 WHERE (STUDENT_ADDRESS LIKE '%강원도%' OR STUDENT_ADDRESS LIKE '%경기도%')
       AND STUDENT_NO LIKE '9%'
 ORDER BY 1;
 
-- 4.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
  FROM TB_PROFESSOR
       JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
 WHERE DEPARTMENT_NAME = '법학과' 
 ORDER BY EXTRACT(YEAR FROM SYSDATE) - TO_NUMBER('19' || SUBSTR(PROFESSOR_SSN, 1, 2)) DESC;
 
SELECT PROFESSOR_NAME, PROFESSOR_SSN
  FROM TB_PROFESSOR
       JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
 WHERE DEPARTMENT_NAME = '법학과' 
 ORDER BY SUBSTR(PROFESSOR_SSN, 1, 2); 
 
-- 5.
SELECT STUDENT_NO, TO_CHAR(POINT, 9.99) POINT
  FROM TB_GRADE
 WHERE TERM_NO = '200402'
       AND CLASS_NO = 'C3118100'
 ORDER BY 2 DESC, 1;
 
-- 6.
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
  FROM TB_STUDENT
       JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
 ORDER BY 2;
 
-- 7.
SELECT CLASS_NAME, DEPARTMENT_NAME
  FROM TB_CLASS
       JOIN TB_DEPARTMENT USING (DEPARTMENT_NO);
--.. 데이터가 너무 많다면, COUNT 함수로 개수를 확인하는 방법도 ...       
       
-- 8.
SELECT CLASS_NAME, PROFESSOR_NAME
  FROM TB_CLASS_PROFESSOR
       JOIN TB_CLASS USING (CLASS_NO)
       JOIN TB_PROFESSOR USING (PROFESSOR_NO);
       
-- 9.
SELECT CLASS_NAME, PROFESSOR_NAME
  FROM TB_CLASS_PROFESSOR
       JOIN TB_CLASS USING (CLASS_NO)
       JOIN TB_PROFESSOR P USING (PROFESSOR_NO)
       JOIN TB_DEPARTMENT D ON P.DEPARTMENT_NO = D.DEPARTMENT_NO
       --> USING을 사용할 수 없는 이유: 동일한 이름의 컬럼이 3개 이상의 테이블에서 사용됨
       --  >> TB_PROFESSOR, TB_DEPARTMENT, TB_CLASS 테이블에서 DEPARTMENT_NO 컬럼으로 모두 사용중!
WHERE CATEGORY = '인문사회';

-- 10.
SELECT STUDENT_NO 학번, STUDENT_NAME "학생 이름", ROUND(AVG(POINT), 1) "전체 평점"
FROM TB_STUDENT
    JOIN TB_GRADE USING (STUDENT_NO)
    JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '음악학과'
GROUP BY STUDENT_NO, STUDENT_NAME;

-- 11.
SELECT DEPARTMENT_NAME 학과이름, STUDENT_NAME 학생이름, PROFESSOR_NAME 지도교수이름
FROM TB_STUDENT
     JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
     JOIN TB_PROFESSOR ON PROFESSOR_NO = COACH_PROFESSOR_NO
WHERE STUDENT_NO = 'A313047';

-- 12.
SELECT STUDENT_NAME, TERM_NO TERM_NAME
  FROM TB_GRADE
       JOIN TB_STUDENT USING (STUDENT_NO)
       JOIN TB_CLASS C USING (CLASS_NO)
 WHERE TERM_NO LIKE '2007%'
   AND CLASS_NAME = '인간관계론';
   
-- 13.
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
     LEFT JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
     LEFT JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE CATEGORY = '예체능'
      AND PROFESSOR_NO IS NULL;


-- 14.
SELECT STUDENT_NAME 학생이름, NVL(PROFESSOR_NAME, '지도교수 미지정') 지도교수
FROM TB_STUDENT S
     LEFT JOIN TB_PROFESSOR ON(PROFESSOR_NO = COACH_PROFESSOR_NO)
     JOIN TB_DEPARTMENT D ON(S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '서반아어학과'
ORDER BY STUDENT_NO;

-- 15.
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, DEPARTMENT_NAME "학과 이름", TRUNC(AVG(POINT), 8) 평점
FROM TB_STUDENT
     JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
     JOIN TB_GRADE USING(STUDENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
HAVING AVG(POINT) >= 4.0
ORDER BY 1;

-- 16.
SELECT CLASS_NO, CLASS_NAME, TRUNC(AVG(POINT),8) "AVG(POINT)"
FROM TB_CLASS
     JOIN TB_GRADE USING(CLASS_NO)
     JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '환경조경학과'
      AND CLASS_TYPE LIKE '전공%'
GROUP BY CLASS_NO, CLASS_NAME
ORDER BY 1;

-- 17.
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO
                       FROM TB_STUDENT
                       WHERE STUDENT_NAME = '최경희');
                       
-- 18.
SELECT STUDENT_NO, STUDENT_NAME
FROM (SELECT STUDENT_NO, STUDENT_NAME, AVG(POINT)
      FROM TB_GRADE
           JOIN TB_STUDENT USING(STUDENT_NO)
      WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO
                             FROM TB_DEPARTMENT
                             WHERE DEPARTMENT_NAME = '국어국문학과')
      GROUP BY STUDENT_NO, STUDENT_NAME
      ORDER BY AVG(POINT) DESC)
WHERE ROWNUM = 1;

SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
     JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
     JOIN TB_GRADE USING(STUDENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과'
GROUP BY STUDENT_NO, STUDENT_NAME
HAVING AVG(POINT) = (SELECT MAX(AVG(POINT))
                     FROM TB_GRADE
                     WHERE STUDENT_NO IN (SELECT STUDENT_NO
                                         FROM TB_STUDENT
                                         WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO
                                                                FROM TB_DEPARTMENT
                                                                WHERE DEPARTMENT_NAME = '국어국문학과'))
                     GROUP BY STUDENT_NO);

SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
     JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
     JOIN TB_GRADE USING(STUDENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과'
GROUP BY STUDENT_NO, STUDENT_NAME
HAVING AVG(POINT) = (SELECT MAX(AVG(POINT))
                     FROM TB_GRADE
                          JOIN TB_STUDENT USING(STUDENT_NO)
                          JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
                     WHERE DEPARTMENT_NAME = '국어국문학과'
                     GROUP BY STUDENT_NO);
                     
-- 19.
SELECT DEPARTMENT_NAME "계열 학과명", ROUND(AVG(POINT), 1)
FROM TB_DEPARTMENT
     JOIN TB_STUDENT USING(DEPARTMENT_NO)
     JOIN TB_GRADE USING(STUDENT_NO)
WHERE CATEGORY = (SELECT CATEGORY
                  FROM TB_DEPARTMENT
                  WHERE DEPARTMENT_NAME = '환경조경학과')
GROUP BY DEPARTMENT_NAME
ORDER BY 1;