CREATE TABLE CUSTOMER (
    CUST_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100),
    BIRTHDATE DATE,
    ADDRESS VARCHAR2(200)
);

INSERT INTO CUSTOMER (CUST_ID, NAME, BIRTHDATE, ADDRESS) VALUES (1, '마이유', TO_DATE('1993-05-16', 'YYYY-MM-DD'), '서울특별시 강남구');
INSERT INTO CUSTOMER (CUST_ID, NAME, BIRTHDATE, ADDRESS) VALUES (2, '막보검', TO_DATE('1993-06-16', 'YYYY-MM-DD'), '부산광역시 해운대구');
INSERT INTO CUSTOMER (CUST_ID, NAME, BIRTHDATE, ADDRESS) VALUES (3, '두지', TO_DATE('1994-10-10', 'YYYY-MM-DD'), '대구광역시 수성구');
INSERT INTO CUSTOMER (CUST_ID, NAME, BIRTHDATE, ADDRESS) VALUES (4, '이빈호', TO_DATE('1987-06-22', 'YYYY-MM-DD'), '인천광역시 연수구');
INSERT INTO CUSTOMER (CUST_ID, NAME, BIRTHDATE, ADDRESS) VALUES (5, '강수현', TO_DATE('1988-02-16', 'YYYY-MM-DD'), '경기도 성남시 분당구');
INSERT INTO CUSTOMER (CUST_ID, NAME, BIRTHDATE, ADDRESS) VALUES (6, '함지민', TO_DATE('1982-11-05', 'YYYY-MM-DD'), '서울특별시 서초구');
INSERT INTO CUSTOMER (CUST_ID, NAME, BIRTHDATE, ADDRESS) VALUES (7, '곰유', TO_DATE('1979-07-10', 'YYYY-MM-DD'), '부산광역시 수영구');
INSERT INTO CUSTOMER (CUST_ID, NAME, BIRTHDATE, ADDRESS) VALUES (8, '소예진', TO_DATE('1982-01-11', 'YYYY-MM-DD'), '서울특별시 강서구');
INSERT INTO CUSTOMER (CUST_ID, NAME, BIRTHDATE, ADDRESS) VALUES (9, '정구성', TO_DATE('1973-03-20', 'YYYY-MM-DD'), '서울특별시 용산구');
INSERT INTO CUSTOMER (CUST_ID, NAME, BIRTHDATE, ADDRESS) VALUES (10, '김대리', TO_DATE('1990-04-24', 'YYYY-MM-DD'), '경기도 고양시 일산동구');

COMMIT;